### ISSUE TITLE
Абстрактный интерфейс модели

### ISSUE THREAD

**Issue by Rabbitlancer** [moevm/gui-1h2018-17#11]
Необходимо реализовать простой класс со следующими геттерами (достаточно заглушек, но лучше, чтоб работало):
- [x] вернуть список персонажей
- [x] вернуть список сцен
- [x] вернуть список параметров по персонажу
- [x] вернуть список эффектов по персонажу
- [x] вернуть полное описание с эффектами в текстовом виде, по персонажу
- [x] вернуть полное описание по сцене

**Comment by Rabbitlancer** [comment]
https://github.com/moevm/gui-1h2018-17/pull/14

**Comment by MilanaGaiduk** [comment]
https://github.com/moevm/gui-1h2018-17/pull/15

**Comment by MilanaGaiduk** [comment]
https://github.com/moevm/gui-1h2018-17/pull/15
