### ISSUE TITLE
Реализация вкладки "Настройка"

### ISSUE THREAD

**Issue by Rabbitlancer** [moevm/gui-1h2018-17#5]
Необходимо реализовать:
- [x] переключающиеся подвкладки (группами или панелями)
- [x] панель "настройка параметров"
- [x] панель "настройка инициативы"
- [x] панель "настройка эффектов"
- [x] реализовать маленькие "формы i"
Подзадача:
- [x] форма подтверждения удаления (#7 )

**Comment by MilanaGaiduk** [comment]
https://github.com/moevm/gui-1h2018-17/tree/configuration_tab

**Comment by MilanaGaiduk** [comment]
https://github.com/moevm/gui-1h2018-17/pull/9

**Comment by MilanaGaiduk** [comment]
Подзадачу с формой i переназначила на RabbitLancer
